<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class AddressRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'street' => 'required',
            "neighborhood" => 'required',
            "number_house"=> 'required|numeric',
            "complements"=> 'required',
            "city" => 'required',
            "state" => 'required|max:2',
            "reference_point" => 'required',
        ];
    }


    public function messages()
    {
        return [
            "required" => "Este campo é obrigatorio",
            "numeric" => "Tem que ser numero"
        ]; // TODO: Change the autogenerated stub
    }
}
